language: cpp

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
	
env: CC=gcc-6 CXX=g++-6
  
compiler:
  - clang
  - gcc
  
script:
  - export OMP_NUM_THREADS=4
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" "../" && make
